version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: standard-version
    versions:
    - 9.1.0
    - 9.1.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
